43- Accept a number and print its reverse

In [13]:
n = int(input())

ar=0
while(n!=0):
    a= n%10
    ar= ar*10+a
    n= n//10
print(ar)
    
    


321


In [15]:
arr=[[1,2,3],[2,3,4],[7,8,9],[0,5,4],[8,9,7]]
print(arr)

[[1, 2, 3], [2, 3, 4], [7, 8, 9], [0, 5, 4], [8, 9, 7]]


In [16]:
arr=[]
for i in range(0,20):
    arr.append(i)
    i=i-1
print(arr)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]


In [ ]:
arr=[[[[ ]]]]

In [18]:
## identity matrix 5x5
import numpy as np 
ar = np.eye(5,5)
print(ar)


[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [19]:
import numpy
arr = numpy.empty(4)
print(arr)

[0.00000000e+000 1.07179897e-311 1.07179897e-311 1.07179897e-311]


In [5]:
if __name__ == '__main__':
    bag=[]
    for _ in range(int(input())):
        name = input()
        score = float(input())
        bag.append([name,score])
    
    second= sorted(list(set([x[1] for x in bag])))
    print(second)
    

[2.0, 3.0]


In [13]:
n = int(input())
list= []
for x in range(n):   
    inpt= input().split()
    if (inpt[0]=="append"):
        list.append(int(inpt[1]))
    elif(inpt[0]=="insert"):
        list.insert(int(inpt[1]),int(inpt[2]))
    elif(inpt(0)== "print"):
        print(list)
    elif(inpt(0)=="sort"):
        list.sort()
    elif(inpt(0)=="reverse"):
        list.reverse()
    elif(inpt(0)=="pop")
        list.pop()


[2, 1]


In [5]:
51%2


1


 
# Calling above method over this array set
print(findLargest([10, 20, 4, 45, 99]))

In [2]:
def findLargest(arr):
    secondLargest = 0
    largest = min(arr)
 
    for i in range(len(arr)):
        if arr[i] > largest:
            secondLargest = largest
            largest = arr[i]
        else:
            secondLargest = max(secondLargest, arr[i])
 
    # Returning second largest element
    return secondLargest
 
 
# Calling above method over this array set
print(findLargest([10, 20, 99, 45, 99]))

99


In [19]:
if __name__ == '__main__':
    n = int(input())
    y=0
    a = list(map(int, input().strip().split()))
    maxim= max(list(a))
    srt= a.sort()
    for i in range(n-1,0):
        if (srt[i]!= maxim):
            srt[i]=y
            break
    print(y)
        
        
        
   


0


In [23]:
if __name__ == '__main__':
    n = int(input())
    a = list(map(int, input().strip().split()))
    
    # Find the maximum element
    maxim = max(a)
    
    # Remove duplicates and sort the list in ascending order
    unique_sorted = sorted(set(a))
    
    # If there are at least two unique elements
    if len(unique_sorted) >= 2:
        
        second_largest = unique_sorted[-2]
        print(second_largest)
    else:
        # There is no second largest element
        print("There is no second largest element.")


5


In [14]:
for i in range(0,6):
    for j in range(0,6):
        print('*', end='')
        i=i-1
print("*")
    


*************************************


68- Take 2 numbers as inputs and find their HCF.

In [10]:
number1,number2= map(int,input().split())

a= min(number1,number2)

hcf=1

for i in range(1,a):
     if (number1%i==0 and number2%i==0):
          hcf=i
          
print(hcf)
     


6


In [ ]:
n= int(input())
for i in range (1,n-1):
    for j in range(0,)
    